services:
  - type: web
    name: arkadasai-demo-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEMO_SECRET
        generateValue: true